### ISSUE TITLE
Any Sass port ?

### ISSUE THREAD

**Issue by labo-css** [husl-colors/husl#18]
Hello, i really love this concept but i fail to find any sass implementation or working alternative. Have you any clue for how to make this work in plain css via sass? Thanx.

**Comment by boronine** [comment]
Hi Nicolas, sadly no such port exists, though it's been on my mind for a long time. There is an incomplete Ruby port here: https://github.com/soulcutter/husler. If this port was completed, Sass integration should be pretty easy.

**Comment by labo-css** [comment]
Damn, that's too bad, this project is like public service to me, he redefine the relation designers and dev have with colors. Too many time people are using themes with sass and "hop" 90° hue shift and i have a new template. But... this is not that easy, almost everytime contrast fail and type are not readable. Husl fix this problem. And... husl is in javascript :/

Templates do not have to depend on JS, but this tool fixes so many problems. I hope someone will have the time and knowledge to port it on Sass :)

**Comment by boronine** [comment]
Nicolas, thank you for the encouraging words. Maybe I'll get around to it after all. I would say Sass is the most important target for HUSL right now. I'll leave this issue open.

**Comment by radubogdan** [comment]
I want to work on this. Let me find some time to start it and we can have a chat about it :+1:

**Comment by boronine** [comment]
Excellent! Look forward to hearing from you, @radubogdan.

**Comment by labo-css** [comment]
Dreams coming alive :+1:

**Comment by radubogdan** [comment]
@boronine  Hey, I finished the port. The other one was old and didn't want to deal with legacy code.

Here it is: https://github.com/radubogdan/husl

@labo-css Please send me an email with details about the sass-husl. Should be easy enough now :)
I don't know how you imagine it'll work so please explain it to me.

Please open issues on Github if you spot any errors. Feel free to fork, star and PR :)

**Comment by labo-css** [comment]
I really do not know how to made it work in sass, or with gulp. I just want some mixins/functions.
Never worked with ruby, sorry i can't help.

**Comment by boronine** [comment]
@radubogdan fantastic!

I've posted to https://groups.google.com/forum/#!forum/sass-lang asking for some guidance, hopefully someone familiar with the Sass ecosystem can weigh in on this.

@labo-css I was reading more about Sass today and its libsass implementation. Is that what you use? Do you invoke it from another programming language or do you just use Sass as a binary?

**Comment by radubogdan** [comment]
Hey,

I don't think it's complicated at all. Perhaps integrating it deep into core, or replace hsl with husl is harder, but defining some functions for sass binary should be a matter of monkeypatching.

I will keep an eye today on the mailing list, and try something tonight ;)

**Comment by labo-css** [comment]
@boronine @radubogdan I use libsass, if you want to add husl to sass i advise you to treat it like bourbon does it. http://bourbon.io/

A npm package usable with gulp, and basically everything that use npm.

**Comment by radubogdan** [comment]
@labo-css I don't have too much time to read about this, but I've created a ruby file and you can invoke it in your sass command.

**Ruby script [husl-sass.rb]:**
```
require 'husl'

module Sass::Script::Functions
  module HuslSass
    def husl h, s, l
      hex = Husl.husl_to_hex(h.to_s.to_f, s.to_s.to_f, l.to_s.to_f)
      Sass::Script::Value::String.new(hex)
    end
  end

  include HuslSass
end
```

**Example of file [test.sass]:**
```
body
  background-color: husl(100, 43, 50)
```

**Command:**
```
sass test.sass test.css -r ~/path/to/script/husl-sass.rb
```

**Output:**
```
body {
  background-color: #717b58; }
```

Also I think you can put it iniside `initializers` directory in rails, and you can basically start using `husl` function in any sass file.

I will read more about it and create a gem with multiple mixins to be more user-friendly.

**Comment by epiloque** [comment]
just finished a node-sass only husl/huslp https://github.com/epiloque/node-sass-husl

**Comment by radubogdan** [comment]
This is great @epiloque. Welcome to the team :) 

I think is great that is working with gulp and most definitely is better than my monkeypatched version ! I'll play with it later today. Good job :+1:

**Comment by epiloque** [comment]
@radubogdan thank you!

**Comment by boronine** [comment]
@epiloque very cool!

**Comment by boronine** [comment]
Interesting: Bootstrap 4 will use Sass instead of Less: http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/

**Comment by boronine** [comment]
Sass port completed by @apexskier https://github.com/apexskier/husl-sass

The issue is resolved!
