### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by mnpenner** [husl-colors/husl#19]
Pretty sure you've got a division by zero error in `conv.xyz.luv`.

```js
  conv.xyz.luv = function(tuple) {
    var L, U, V, X, Y, Z, varU, varV;
    X = tuple[0], Y = tuple[1], Z = tuple[2];
    varU = (4 * X) / (X + (15 * Y) + (3 * Z));
    varV = (9 * Y) / (X + (15 * Y) + (3 * Z));
    L = Y_to_L(Y);
    if (L === 0) {
      return [0, 0, 0];
    }
    U = 13 * L * (varU - refU);
    V = 13 * L * (varV - refV);
    return [L, U, V];
  };
```

If `X`, `Y`, and `Z` are 0, or that equation sums to 0, the denom will be 0. I think moving the `L === 0` check above the `varU`/`varV` computation will fix that.

It doesn't error out since JS just returns `NaN` but it's a fatal error in PHP which I'm trying to port.

**Comment by boronine** [comment]
Great catch, thank you!
