### ISSUE TITLE
Upside down gamut

### ISSUE THREAD

**Issue by baskerville** [husl-colors/husl#20]
The [interactive gamut widget](http://www.husl-colors.org/) is upside down. (The yellow *primary* is close to 90°.)

**Comment by Lucas-naceri** [comment]
Yellow LCHuv hue: ~85.9°

**Comment by boronine** [comment]
Upside-down? Which way do you think it should be turned exactly?

**Comment by baskerville** [comment]
If you set the hue slider to 90°, the little circle indicate 270° (actually, the whole widget is flipped relative to the *x*-axis).

My guess is that you have a small sign mistake in your code: something like `cy + r*sin(a)` instead of `cy - r*sin(a)`.

**Comment by boronine** [comment]
I just Google image-d for "CIE LUV" and now I see that it is indeed upside-down. I had a hard time understanding the reference point relative to which it was misaligned. Moving this issue: https://github.com/husl-colors/husl-site/issues/13
