### ISSUE TITLE
the pastrel variant results in out of bounds saturation value

### ISSUE THREAD

**Issue by epiloque** [husl-colors/husl#24]
The husl pastrel variant outputs a out of bounds saturation value.
 
```javascript
> husl.p.fromRGB(0, 0, 0.5)
[ 265.87432021817733, 513.4126968442829, 8.646890129976928 ]
```

Thank you

**Comment by boronine** [comment]
Actually, the problem here is that RGB (0, 0, 0.5) is not in the HUSLp gamut, it's too saturated. I'm guessing you want to use HUSL rather than HUSLp if you're converting RGB to it. I'm going to add a note to the README. Thanks for the report!

**Comment by epiloque** [comment]
Got it, thanks!
