### ISSUE TITLE
HSL to HUSL?

### ISSUE THREAD

**Issue by polarathene** [husl-colors/husl#25]
I noticed the website has a hue picker, and it looks like it's displaying HSL values along with a hex. Is this slider input being used to produce HUSL at all? It wasn't clear to me beyond the visual colour space (chroma?) changing and the dot for colour moving through it. I wanted to use this library but it didn't seem like it was friendly for stepping through the hues, there doesn't seem to be documentation on it's value range? When trying the Lua version out I was getting hue values all over the place as I moved through the hues incrementally:

Progressively moving along the hue range from 0 to 359.5
```
6.7535548210144
636.54663085938
1390.5018310547
3776.076171875
6971.8715820313
5463.1713867188
1969.6057128906
336.37377929688
```

husl/huslp to rgb function seems to convert the colour fine. But I guess there isn't a programmatic way to cycle through the hue like with HSL? Perhaps a function could be used for this?

**Comment by boronine** [comment]
Hi Brennan,

The H, S, L sliders on the homepage represent HUSL values, not HSL values, which might be the source of confusion here. There is some further confusion with the issue of stepping through the hues. To step through the hues with HUSL, you would need to do something like this (pseudocode):

```
for (i=0; i<10; i++) { huslToRgb(i * 36, 50, 50); }
```

The numbers you provided seem to be incorrect, but I'm not sure how exactly you generated them. If I understand you correctly they are hue values? But you generated them by stepping though other hue values? Could you explain that?

**Comment by polarathene** [comment]
This is a test snippet for the above results in a games lua engine,`log()` is just to print to the games console and log file.

```
log("hex to huslp1: " .. tostring(HUSL:getHUSL().hex_to_husl('#ea0064')))
log("hex to huslp2: " .. tostring(HUSL:getHUSL().hex_to_husl('#ef001d')))
log("hex to huslp3: " .. tostring(HUSL:getHUSL().hex_to_husl('#c85300')))
log("hex to huslp4: " .. tostring(HUSL:getHUSL().hex_to_husl('#8f7400')))
log("hex to huslp5: " .. tostring(HUSL:getHUSL().hex_to_husl('#388800')))
log("hex to huslp6: " .. tostring(HUSL:getHUSL().hex_to_husl('#006ffd')))
log("hex to huslp7: " .. tostring(HUSL:getHUSL().hex_to_husl('#d900bd')))
log("hex to huslp8: " .. tostring(HUSL:getHUSL().hex_to_husl('#ea0066')))
```

You can see that I sampled the hex code from the slider as I stepped through it(not perfect steps). I did this since using hue values of 0-360 which I would have assumed HUSL would use was always producing red. No idea why the number is so large, the colours are correct when using `hex_to_husl`.

I would apply the colours like so:
`colour = Vector3( HUSL:getHUSL().huslp_to_rgb( HUSL:getHUSL().hex_to_huslp('#39a467')) )`
If I understand correctly, `huslp` is similar to `husl` but slightly better choice? If I could step through the hues with a loop like I could with HSL that'd be great :)

The only change I've made to the class is to wrap it in:

```
if not _G.HUSL then
    _G.HUSL = {}

    function HUSL:getHUSL()
        -- Rest of code here
    end
end
```

**Comment by boronine** [comment]
Hi Brennan, I just did the following test to confirm that HUSL generated correct numbers for the hex colors you provided:

```
Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio
> husl = require 'husl'
> = husl.hex_to_husl('#ea0064')
0.11786819154934	99.999999999999	49.999461028217
> = husl.hex_to_husl('#ef001d')
11.109833607508	100	50.03227766649
> = husl.hex_to_husl('#c85300')
24.26885039576	100	50.060878557424
> = husl.hex_to_husl('#8f7400')
65.904978665339	100	49.895842364182
> = husl.hex_to_husl('#388800')
121.68214034739	100	50.035253204047
> = husl.hex_to_husl('#006ffd')
258.3664850745	100.00000000001	50.046382454934
> = husl.hex_to_husl('#d900bd')
319.34071134768	99.999999999998	50.013097245283
> = husl.hex_to_husl('#ea0066')
359.58763950098	99.999999999999	50.046245526067
```

I'm not sure where those big numbers are coming from, but they don't seem to be coming from HUSL. If you still believe the problem is with HUSL, please give me the shortest snippet you can that would demonstrate it (just one color, no wrapper functions etc.).

I may be able to help you further if you tell me what you are trying to use HUSL for. Usually using HUSL involves generating HUSL coordinates (stepping through hues is a common example) and converting the HUSL color to RGB or hex in order to display it.

**Comment by polarathene** [comment]
I was just after a lua class/functions to handle colour manipulation better, specifically HSL and I stumbled upon HUSL which seemed it might be a better option. 

All I plan to do is take a number value that is divided by the hue range 0-360 and returns a table/array of colours, so 4 would return 4 colours using the hue values 0, 90, 180, 270. The hex conversion here was to troubleshoot why hue values between 0-360 were all returning red rgb, from memory the `hex -> husl -> rgb` conversion resulted in the correct colour but those odd numbers for the hue channel.

Apart from the wrapper function the actual code is being used for modding a game that uses Lua, it might be the code is conflicting somewhere with it? I've setup [this REPL example](https://repl.it/CFBX/0) which is how I remember implementing your class(not at home right now). It seems to function correctly.

I'll close this as the problem seems to be due to my Lua environment and not your code.

**Comment by polarathene** [comment]
If anyone comes across this issue, the problem was due to my Lua environment using degrees for input and return values for the math functions, whereas the lua implementation uses radians.
