### ISSUE TITLE
any plans to make a glsl port?

### ISSUE THREAD

**Issue by williammalo** [husl-colors/husl#27]
Is it even possible?
Sometimes you need to do color manipulation on the gpu for performance reasons.

**Comment by williammalo** [comment]
If implementing maxChromaForLH is impossible, we could use a lookup texture
![maxchromaforlh](https://cloud.githubusercontent.com/assets/1521848/16903454/9d597b44-4c4c-11e6-96b6-25292e09dbfc.png)

**Comment by boronine** [comment]
No plans at the moment, but the idea is intriguing. I don't have experience with GLSL, I only know that there are limitations to GPU programming, however my feeling is that is should be possible. A lookup texture is a fine solution.

I'm going to leave this issue open.

**Comment by williammalo** [comment]
I'm going to make it myself then, I will keep you updated on my progress :D

**Comment by williammalo** [comment]
It works!
Heres an ugly demo page (use the slider to change lightness)
http://maloweb.com/snippets/webgl-husl.html
Most of the work is still ahead of me, but now I at least know that it's possible.

**Comment by boronine** [comment]
Wow, it's so responsive!! Do you indent on open sourcing this code? It would be a great addition to our project.

**Comment by williammalo** [comment]
Yes, I will put it on github when it's done

**Comment by williammalo** [comment]
I'm at the testing phase now, look at those gorgeous gradients :D
![husl](https://cloud.githubusercontent.com/assets/1521848/16954451/ec50f0f8-4d9e-11e6-8b98-a793e54bf475.png)
![huslp](https://cloud.githubusercontent.com/assets/1521848/16954453/ec5e573e-4d9e-11e6-83bf-010e8f23c796.png)
![lch](https://cloud.githubusercontent.com/assets/1521848/16954454/ec5ea19e-4d9e-11e6-8de2-505e21711bf5.png)
![luv](https://cloud.githubusercontent.com/assets/1521848/16954452/ec5e109e-4d9e-11e6-9e0a-f70136f97e15.png)
![xyz](https://cloud.githubusercontent.com/assets/1521848/16954455/ec5f0df0-4d9e-11e6-9fd1-f25f505b5baa.png)
http://maloweb.com/snippets/webgl-husl.html

**Comment by boronine** [comment]
Those are gorgeous! It would be awesome to integrate it into the color picker on the home page, I was forced to make the current one rather small and pixely to avoid taxing the CPU.

**Comment by williammalo** [comment]
Oh yeah, that would be great! I will try to get antialiasing on the edges to make it look better!

**Comment by williammalo** [comment]
I'm not satisfied with my lookup table approach, but I decided to release early https://github.com/williammalo/husl-glsl

**Comment by williammalo** [comment]
YES! I managed to implement maxChromaForLH without using lookup textures!
Now the math is more accurate and it's way easier to set up!
https://github.com/williammalo/husl-glsl
Test page updated with latest version + antialiasing and dithering:
http://maloweb.com/snippets/webgl-husl.html

**Comment by williammalo** [comment]
Now I just need to rewrite your colorpicker ;)

**Comment by boronine** [comment]
Fantastic! I'm going to close this issue and follow up in email.
