### ISSUE TITLE
Swap out reference implementation for Haxe

### ISSUE THREAD

**Issue by boronine** [husl-colors/husl#29]
- [x] Merge husl-haxe into this repo
- [x] Update JavaScript build chain
- [x] Update Travis CI build
- [x] Update READMEs
- [x] Push out new JavaScript build
- [x] Merge into master
- [x] Update homepage

**Comment by Eiyeron** [comment]
Oh, by the way, so you're dropping the haxelib library idea?

**Comment by boronine** [comment]
No, still doing it. Just made a new issue: https://github.com/husl-colors/husl/issues/30
