### ISSUE TITLE
husl node package is broken

### ISSUE THREAD

**Issue by seriousben** [husl-colors/husl#31]
It is missing the husl.js file :)

![screen shot 2016-11-21 at 1 31 07 pm](https://cloud.githubusercontent.com/assets/6145422/20495392/dbf90e54-afee-11e6-9141-a8b342bc1568.png)

**Comment by boronine** [comment]
Thanks for the report! Unpublished the package, working on fix.

**Comment by boronine** [comment]
Fixed in 6.0.3. Thanks again!
