### ISSUE TITLE
Changed Hex output between 6.0.1 and 6.0.3

### ISSUE THREAD

**Issue by nebulon42** [husl-colors/husl#32]
Husl started outputting uppercase letters in the hex output instead of lowercase ones as of 6.0.3. Something like that is strange to happen for a patch release. It breaks some tests downstream at https://github.com/mapbox/carto.

I suggest to either restore the old behaviour or change 6.0.3 to 6.1.0.

**Comment by boronine** [comment]
This is definitely a bug, thanks for the catch! Fixed in 6.0.4.

**Comment by nebulon42** [comment]
Confirmed fixed. Thanks!
